### ISSUE TITLE
[high priority] Darker 3dtiles shading in A-Frame 1.3 compared to A-Frame 1.2

### ISSUE THREAD

**Issue by kfarr** [nytimes/aframe-loader-3dtiles-component#14]
Hi there, after updating a scene to the latest version of A-Frame 1.3 (which includes THREE Version ^0.137.0 from https://github.com/supermedium/three.js) a 3dtiles scene using this loader appears darker than when using A-Frame 1.2 and darker than reference application used to produce 3dtiles output.

Here is the expected output working correctly using a-frame 1.2:
https://3dtiles-aframe-issue-1.glitch.me/aframe120.html
![image](https://user-images.githubusercontent.com/470477/169928672-9fb0fc57-cba1-4515-9199-af055694602b.png)

Here is the unexpected output not working correctly using a-frame 1.3:
https://3dtiles-aframe-issue-1.glitch.me/aframe130.html
![image](https://user-images.githubusercontent.com/470477/169928735-0cf24534-00d8-4b34-8132-f71d0453a798.png)

Here is a reference from Cesium's interface which matches the expected shading when using 3dtiles loader with A-Frame 1.2:
[Link to cesium sandbox](https://sandcastle.cesium.com/?src=Hello%20World.html&label=Showcases&code=eyJjb2RlIjoiLy8gR3JhbnQgQ2VzaXVtSlMgYWNjZXNzIHRvIHlvdXIgaW9uIGFzc2V0c1xuQ2VzaXVtLklvbi5kZWZhdWx0QWNjZXNzVG9rZW4gPSBcImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUpxZEdraU9pSTNZVFl5WVRJek5TMHlPRGcwTFRSaFpXUXRZall4TlMxaU5XTmhaR1poTm1ZM09UZ2lMQ0pwWkNJNk1UY3dOakVzSW5OamIzQmxjeUk2V3lKaGMzSWlMQ0puWXlKZExDSnBZWFFpT2pFMU56RTFPVGN4TnpaOS5SOG1Lby1OaXpjbU9qQ05fNGRReWQ1eE80WDY1NUNaWk1YYTlCNXNFQ3lVXCI7XG5cbmNvbnN0IHZpZXdlciA9IG5ldyBDZXNpdW0uVmlld2VyKFwiY2VzaXVtQ29udGFpbmVyXCIpO1xuXG5jb25zdCB0aWxlc2V0ID0gdmlld2VyLnNjZW5lLnByaW1pdGl2ZXMuYWRkKFxuICBuZXcgQ2VzaXVtLkNlc2l1bTNEVGlsZXNldCh7XG4gICAgdXJsOiBDZXNpdW0uSW9uUmVzb3VyY2UuZnJvbUFzc2V0SWQoMTA1NDUyOSksXG4gICAgLy9UaGlzIHRpbGVzZXQgZG9lc24ndCBoYXZlIGEgbG9jYXRpb24sIHNvIHdlJ3JlIHVzaW5nIGEgbW9kZWxNYXRyaXggdG8gcGxhY2UgaXQgYXQgMCwgMCBpbnN0ZWFkIG9mIGRyYXdpbmcgYXQgdGhlIGNlbnRlciBvZiB0aGUgZWFydGhcbiAgICBtb2RlbE1hdHJpeDogQ2VzaXVtLlRyYW5zZm9ybXMuZWFzdE5vcnRoVXBUb0ZpeGVkRnJhbWUoXG4gICAgICBDZXNpdW0uQ2FydGVzaWFuMy5mcm9tRGVncmVlcygwLCAwKVxuICAgICksXG4gIH0pXG4pO1xuXG4oYXN5bmMgKCkgPT4ge1xuICB0cnkge1xuICAgIGF3YWl0IHRpbGVzZXQucmVhZHlQcm9taXNlO1xuICAgIGF3YWl0IHZpZXdlci56b29tVG8odGlsZXNldCk7XG5cbiAgICAvLyBBcHBseSB0aGUgZGVmYXVsdCBzdHlsZSBpZiBpdCBleGlzdHNcbiAgICB2YXIgZXh0cmFzID0gdGlsZXNldC5hc3NldC5leHRyYXM7XG4gICAgaWYgKFxuICAgICAgQ2VzaXVtLmRlZmluZWQoZXh0cmFzKSAmJlxuICAgICAgQ2VzaXVtLmRlZmluZWQoZXh0cmFzLmlvbikgJiZcbiAgICAgIENlc2l1bS5kZWZpbmVkKGV4dHJhcy5pb24uZGVmYXVsdFN0eWxlKVxuICAgICkge1xuICAgICAgdGlsZXNldC5zdHlsZSA9IG5ldyBDZXNpdW0uQ2VzaXVtM0RUaWxlU3R5bGUoZXh0cmFzLmlvbi5kZWZhdWx0U3R5bGUpO1xuICAgIH1cbiAgfSBjYXRjaCAoZXJyb3IpIHtcbiAgICBjb25zb2xlLmxvZyhlcnJvcik7XG4gIH1cbn0pKCk7XG4iLCJodG1sIjoiPHN0eWxlPlxuICBAaW1wb3J0IHVybCguLi90ZW1wbGF0ZXMvYnVja2V0LmNzcyk7XG48L3N0eWxlPlxuPGRpdiBpZD1cImNlc2l1bUNvbnRhaW5lclwiIGNsYXNzPVwiZnVsbFNpemVcIj48L2Rpdj5cbjxkaXYgaWQ9XCJsb2FkaW5nT3ZlcmxheVwiPlxuICA8aDE+TG9hZGluZy4uLjwvaDE+XG48L2Rpdj5cbjxkaXYgaWQ9XCJ0b29sYmFyXCI+PC9kaXY+XG4ifQ==)
![image](https://user-images.githubusercontent.com/470477/169928927-d90aabcb-909c-4192-aee8-1f705e3a7f08.png)

Workarounds:
- Unsure if there any workarounds except to downgrade to a-frame 1.2

Let me know if there's anything else I can provide to debug. Thanks for the help!

**Comment by kfarr** [comment]
Great, sorry I didn't check the branches, yes we can test this week and report back. I will also test in VR mode to provide feedback on texture jitters on Quest 2.

**Comment by kfarr** [comment]
Confirmed shading appears as expected with the [aframe13 branch](https://github.com/nytimes/aframe-loader-3dtiles-component/tree/aframe13) on Chrome desktop (macOS) browser! As a bonus iOS / Safari looks nice too.

To accomplish sRGB encoded textures, add `renderer="colorManagement: true"` to the `a-scene` tag like this:
`<a-scene renderer="colorManagement: true">`

glitch URL example that uses the aframe13 branch:
https://3dtiles-aframe-issue-1.glitch.me/aframe130-3dtiles130.html

screenshot:
![image](https://user-images.githubusercontent.com/470477/170366517-10e1d321-895a-49d5-a142-7ec1f9f2fc3b.png)

Next step:
Test in VR mode on quest 2

**Comment by kfarr** [comment]
Hi @Avnerus we tested using the [aframe13 branch](https://github.com/nytimes/aframe-loader-3dtiles-component/tree/aframe13) compared to the current main branch.

We do see 2 examples of flickering -- textures in "medium distance" seem to sparkle. Textures in "long distance" sometimes have z-fighting appearance of flickering. 

However, we also see the same issues in the main as well as aframe13 branch, so the new release doesn't seem to be contributing to this issue.

I would suggest to merge aframe13 branch as it is at least handling color better than the current, and even if no improvement to VR situation it is not worse than current.

**Comment by Avnerus** [comment]
Hi @kfarr, thank you for checking this out!
I will have to run some more tests before merging the branch, because when I tested this last I was seeing a clear difference switching back and forth between AFrame 1.2 and 1.3. 
I'll get back to you on this during this week.
/Avner

**Comment by Avnerus** [comment]
Update: I ran some tests and now it doesn't seem like there is a noticeable difference on my headset between the versions, but I am waiting to get some more feedback.
The `aframe13` branch now uses the newest version of `three-loder-3dtiles`. As a heads-up, there is one breaking change regarding the orientation of tilesets. It was incorrectly calculated in previous versions which caused some models to be tilted. This is fixed in the new version.

**Comment by kfarr** [comment]
Ok good to hear and thanks for the heads up on the breaking change, I just happened to notice that last night on a test project using this branch so I'm happy to hear it was intended. FWIW the new orientation seems more "correct" -- the model required less height and rotation adjustment in A-Frame scene to match expected orientation relative to model viewed in Cesium.

**Comment by Avnerus** [comment]
Hi,
This is now published to NPM. 
Closing issue, but feel free to re-open if any problems occur.
