### ISSUE TITLE
[low prio] 3dtiles appears in vertical (90º rotated) orientation for 1 second while loading

### ISSUE THREAD

**Issue by kfarr** [nytimes/aframe-loader-3dtiles-component#15]
Issue: As a user viewing an A-Frame scene that includes this loader-3dtiles-component and a cesium ion hosted 3dtile set, I am disoriented by seeing the 3dtiles mesh rendered 90º for approximately one second while loading a scene.

Expected behavior: The 3dtiles scene should be rotated correctly prior to rendering the scene

Workaround: Set 3dtiles entity visibility to false, add application logic to turn visibility to true after x seconds or upon a load success callback if such a thing exists (not tested)

Screenshots:

Screenshot1 (first visible output from this loader-3dtiles-component approx 1 second after page load):
![image](https://user-images.githubusercontent.com/470477/169929509-23c4e59e-03cc-4b18-a4b8-c0ca95cdfc2a.png)

Screenshot2 (approx 1.5 second after page load, note that some of the tiles are loading with correct rotation):
![image](https://user-images.githubusercontent.com/470477/169929673-f7270460-2649-4b5f-810c-6f9f97bb6f1c.png)

Screenshot3 (approx 2 seconds after page load, now the entire 3dtiles scene is rotated as expected):
![image](https://user-images.githubusercontent.com/470477/169929654-6fb4b090-5171-4b62-b8e4-ceaf613a0c27.png)

Reference URL:

All screenshots from a video recorded of loading this url after cache refresh on 10mbps connection:
https://3dtiles-aframe-issue-1.glitch.me/aframe120.html

**Comment by Avnerus** [comment]
Hi there!
I am currently in low-availability mode so response times may vary.
I think this is something that I fixed in `dev` in [here](https://github.com/nytimes/aframe-loader-3dtiles-component/commit/b1ada25014533423d720a3de5bbbcd04b4b2ed4c). Could you maybe try the `dev` version through jsdelivr?

**Comment by kfarr** [comment]
Thanks Avner, yes we can test the dev branch and let you know how it works, ETA end of week latest.

**Comment by kfarr** [comment]
this is confirmed fixed in the aframe13 branch

**Comment by Avnerus** [comment]
Hi,
This is now published to NPM.
Closing issue, but feel free to re-open if any problems occur.
