### ISSUE TITLE
3dtiles visibility not affected by A-Frame inspector camera(s)

### ISSUE THREAD

**Issue by kfarr** [nytimes/aframe-loader-3dtiles-component#16]
Issue: As a developer using invoking the A-Frame inspector on an A-Frame scene, the 3dtiles scene does not update along with the inspector camera(s).

Expected behavior: When using the A-Frame inspector I expect the 3dtiles scene to render in the entirety of tiles in the field of view of the currently active a-frame inspector camera. When I change the position or rotation of the inspector camera, the 3dtiles scene should load with respect to the active camera.

To reproduce:
1. Go to a scene with a loader-3dtiles-component and a valid reference to a 3dtiles set, such as https://3dtiles-aframe-issue-1.glitch.me/aframe120.html
2. Press ctrl-alt-i to enter the A-Frame inspector.
3. Click on the camera drop down (it says "perspective by default) and choose "top view"
4. Zoom out by scrolling on the mouse wheel or 2-finger scrolling on a trackpad
5. Note the white areas on the bottom of the screen or "behind" the a-frame scene camera that is not displayed as 3dtiles even though tiles do exist
6. Click "back to scene"
7. Click and drag the camera perspective to turn 180º to look behind the default camera position (away from the 3 shapes)
8. Click "inspect scene"
9. Note the empty tiles on the top half of the screen

Screenshots:
Step 5
![image](https://user-images.githubusercontent.com/470477/169942435-9c586d30-e8df-49b4-a2d5-abc5d82eb5f4.png)

Step 9
![image](https://user-images.githubusercontent.com/470477/169942308-8174bd1c-3d0a-45d9-afc2-8a74f6e68c6d.png)

Potential solutions:
- The inspector could be changed to modify the properties of the loader-3dtiles-component to set the active camera to one injected by the inspector
- The component could be modified to detect presence of the inspector and change to the active camera
- Note that with either of those solutions, it may also be necessary to "override" the inspector's default behavior to "pause" components in the scene
- Another idea is to temporarily move the location of the scene camera to a high vantage point (large y value) and point the camera down on the scene immediately prior to entering the inspector to ensure that all tiles are visible

**Comment by Avnerus** [comment]
Hi!
This is something I have also been trying to figure out.
If I remember correctly, the problem was that the inspector does not always trigger `camera-set-active` when changing cameras. If it did, then it should load the missing tiles when you press the _play_ button (the scene has to be running, otherwise the tileset update does not occur).
Is there any way to catch when the inspector is switching cameras without using `camera-set-active` ?

**Comment by kfarr** [comment]
Yes this could be possible. We can add this to our list to explore, it may be a few ~weeks or months~ years before we get to it.

**Comment by kfarr** [comment]
resolved by #39
